### ISSUE TITLE
Support for .NET 5+

### ISSUE THREAD

**Issue by jessejjohnson** [vin-e/Vindation.CMS#1]
I've been patiently awaiting the next update. **When will you introduce support for .NET 5 and beyond?** I would do this myself, if I were a capable developer.

**Comment by jessejjohnson** [comment]
![anyone home?](https://user-images.githubusercontent.com/1378172/144653740-84401bc2-2e2c-4010-9d7f-b8e3730e737a.gif)

**Comment by jessejjohnson** [comment]
![waiting...](https://user-images.githubusercontent.com/1378172/159373422-0b76bf73-2fc8-4fcf-8c7a-191332c81b0f.png)

**Comment by jessejjohnson** [comment]
![waiting...](https://user-images.githubusercontent.com/1378172/159373510-4ab97eaa-006a-4675-b36e-bcf9fbd971bc.gif)

**Comment by vin-e** [comment]
Thank you for looking at this but this project is set to be archived.
